service: serverless-artillery

plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true

provider:
  name: aws
  runtime: nodejs10.x #nodejs12.x TODO version node? version serverless? DAX rompe
  stage: test
  region: us-east-1
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        'Fn::Join':
          - ':'
          -
            - 'arn:aws:lambda'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - 'function'
            - '${self:service}-${opt:stage, self:provider.stage}-loadGenerator*' # must match function name
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource:
        Ref: monitoringAlerts
    - Effect: 'Allow'
      Action:
        - 'cloudwatch:PutMetricData'
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ OnDemandTableTest, Arn ]
        - "Fn::GetAtt": [ ProvisionedTableTest, Arn ]
    - Effect: Allow
      Action:
        - dax:*
      Resource: !GetAtt DAXCluster.Arn
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: !GetAtt SQSQueue.Arn  
functions:
  loadGenerator: 
    handler: handler.handler   
    timeout: 300
    environment:
      TOPIC_ARN:
        Ref: monitoringAlerts
      TOPIC_NAME:
        'Fn::GetAtt':
          - monitoringAlerts
          - TopicName
    events:
      - schedule:
          name: '${self:service}-${opt:stage, self:provider.stage}-monitoring' # !!Do not edit this name!!
          description: The scheduled event for running the function in monitoring mode
          rate: rate(1 minute)
          enabled: false
          input:
            '>>': script.yml
            mode: monitoring
  mock: #API Gateway Mock
    handler: handler.mock
    events:
      - http:
          path: mock
          cors: true
          method: get
          integration: mock
          request:
            template:
              application/json: '{"statusCode": 200}'
          response:
            template: "Hello World Mock"
            statusCodes:
              200:
                pattern: ''

  vanillaHelloWorld: #API Gateway -> Lambda (responde “Hello World”)
    handler: myFunctions/vanilla.handler
    events:
      - http:
          path: vanilla
          cors: true
          method: get
          
  goldenHelloWorld: #API Gateway -> Lambda (con Golden lambda, responde “Hello World!”)
    handler: myFunctions/goldenhw.handler
    events:
      - http: 
          path: goldenhw
          method: get

  goldenHelloWorldLatency: #API Gateway -> Lambda (con Golden lambda, invoca un servicio http - 100% estable pero con latencia de 2000ms)
    handler: myFunctions/goldenhwlat.handler
    events:
      - http: 
          path: goldenhwlat
          method: get

  goldenHelloWorldLatencyKeepAlive: #API Gateway -> Lambda (con Golden lambda, invoca un servicio http - 100% estable pero con latencia de 2000ms, con keep alive)
    handler: myFunctions/goldenhwlatka.handler
    environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    events:
      - http: 
          path: goldenhwlatka
          method: get

  vanillaHelloWorldLatency: #API Gateway -> Lambda (sin Golden lambda, invoca un servicio http - 100% estable pero con latencia de 2000ms)
    handler: myFunctions/vanillahwlat.handler
    environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    events:
      - http: 
          path: vanillahwlat
          method: get
  
  vanillaHelloWorldLatencyKeepAlive: #API Gateway -> Lambda (sin Golden lambda, invoca un servicio http - 100% estable pero con latencia de 2000ms, con keep alive)
    handler: myFunctions/vanillahwlatka.handler
    events:
      - http: 
          path: vanillahwlatka
          method: get

  vanillaCachedHelloWorld: #API Gateway (con Caché activado) -> Lambda (responde “Hello World”)
    handler: myFunctions/vanillaCached.handler
    events:
      - http:
          path: vanillaCached
          cors: true
          method: get
          caching:
            enabled: true

  vanillaAuthorizer: #API Gateway (con el Authorizer de Shared Services) -> Lambda
    handler: myFunctions/vanillaAuthorizer.handler
    events:
      - http:
          path: vanillaAuthorizer
          method: get
          authorizer: 
            name: authorizerFunction
            type: request
            identitySource: method.request.querystring.authorization
  
  authorizerFunction:
    handler: myFunctions/authorizerFunc.handler
    
  vanillaDynamoProv: #API Gateway -> Lambda -> DynamoDB (Default Capacity)
    handler: myFunctions/vanillaDynamoProv.handler
    events:
      - http:
          path: vanillaDynamoProv
          method: get

  vanillaDynamoOD: #API Gateway -> Lambda -> DynamoDB (On - Demand Capacity)
    handler: myFunctions/vanillaDynamoOD.handler
    events:
      - http:
          path: vanillaDynamoOD
          method: get

  vanillaDynamoDAX: #API Gateway -> Lambda -> Dynamo (con caché DAX)
    handler: myFunctions/vanillaDynamoDAX.handler
    environment:
      DAX_ENDPOINT: { Fn::GetAtt: [DAXCluster, ClusterDiscoveryEndpoint] }
    vpc:
      securityGroupIds:
        - Fn::GetAtt: [DAXSecurityGroup, GroupId]
      subnetIds:
        - Ref: DAXSubnet
    events:
      - http:
          path: vanillaDynamoDAX
          method: get

  vanillaSQS: #API Gateway -> Lambda -> SQS
    handler: myFunctions/vanillaSQS.handler
    events:
      - http:
          path: vanillaSQS
          method: get

  
resources:
  Resources:
    monitoringAlerts: # !!Do not edit this name!!
      Type: 'AWS::SNS::Topic'
      Properties:
        DisplayName: '${self:service} Monitoring Alerts'
    OnDemandTableTest:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OnDemandTableTest
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    ProvisionedTableTest:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProvisionedTableTest
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

    DAXCluster:
      Type: AWS::DAX::Cluster
      Properties:
        ClusterName: daxcluster
        Description: Dax Cluster 
        IAMRoleARN: !GetAtt DAXRole.Arn
        NodeType: dax.t2.small
        ReplicationFactor: 1
        SecurityGroupIds: 
          - !GetAtt DAXSecurityGroup.GroupId
        SubnetGroupName: !Ref DAXSubnetGroup

    DAXRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Action:
              - sts:AssumeRole
              Effect: Allow
              Principal:
                Service:
                - dax.amazonaws.com
          Version: '2012-10-17'
        RoleName: DAXRoleForTesting
        Policies:
          -
            PolicyName: DAXAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Resource: '*'
                  Action:
                    - 'dynamodb:DescribeTable'
                    - 'dynamodb:GetItem'
                    - 'dynamodb:PutItem'
                    - 'dynamodb:Query'
                    - 'dynamodb:Scan'

    DAXSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security Group for DAX
        GroupName: DAX SG
        VpcId: !Ref DAXVPC
  
    DAXSecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      DependsOn: 
        - DAXSecurityGroup
      Properties:
        GroupId: !GetAtt DAXSecurityGroup.GroupId
        IpProtocol: tcp
        FromPort: 8111
        ToPort: 8111
        SourceSecurityGroupId: !GetAtt DAXSecurityGroup.GroupId
    
    DAXVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsHostnames: true
        EnableDnsSupport: true
        InstanceTenancy: default
        Tags:
          - Key: Name
            Value: DAXTest

    DAXSubnet:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone:
          Fn::Select:
            - 0
            - Fn::GetAZs: ''
        CidrBlock: 10.0.0.0/20
        Tags:
          - Key: Name
            Value: DAXTest
        VpcId: !Ref DAXVPC
    
    DAXSubnetGroup:
      Type: AWS::DAX::SubnetGroup
      Properties:
        Description: Subnet group for DAX Test
        SubnetGroupName: DAXTestGN
        SubnetIds: 
          - !Ref DAXSubnet

    SQSQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "SQSQueue"